-- Run this entire file in Supabase SQL Editor.
-- Each user's rows are protected by Row Level Security.

create table if not exists public.schedule_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  subject text not null,
  topic text,
  start_time time not null,
  end_time time,
  created_at timestamptz not null default now()
);

create table if not exists public.study_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  study_date date not null,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  hours numeric(5,2) not null check (hours > 0),
  created_at timestamptz not null default now()
);

create index if not exists schedule_user_day_idx
  on public.schedule_items(user_id, day_of_week, start_time);

create index if not exists logs_user_date_idx
  on public.study_logs(user_id, study_date, created_at);

alter table public.schedule_items enable row level security;
alter table public.study_logs enable row level security;

drop policy if exists "Users can view own schedule" on public.schedule_items;
create policy "Users can view own schedule"
on public.schedule_items for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own schedule" on public.schedule_items;
create policy "Users can insert own schedule"
on public.schedule_items for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own schedule" on public.schedule_items;
create policy "Users can update own schedule"
on public.schedule_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own schedule" on public.schedule_items;
create policy "Users can delete own schedule"
on public.schedule_items for delete
using (auth.uid() = user_id);

drop policy if exists "Users can view own logs" on public.study_logs;
create policy "Users can view own logs"
on public.study_logs for select
using (auth.uid() = user_id);

drop policy if exists "Users can append own logs" on public.study_logs;
create policy "Users can append own logs"
on public.study_logs for insert
with check (auth.uid() = user_id);

-- Logs are intentionally not given update/delete policies.
-- This makes the study log append-only from the website.
